In [4]:
import pandas as pd

SHOPEE

In [107]:
df = pd.read_excel('D:\Dev\Tetris\Data Merge\SHOPEE_SAMPLE 1.xlsx')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\MasAm\AppData\Local\Temp\ipykernel_13044\1792309938.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_excel('D:\Dev\Tetris\Data Merge\SHOPEE_SAMPLE 1.xlsx')

In [7]:
df.columns

Index(['No. Pesanan', 'Status Pesanan', 'Status Pembatalan/ Pengembalian',
       'No. Resi', 'Opsi Pengiriman', 'Antar ke counter/ pick-up',
       'Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan)',
       'Waktu Pengiriman Diatur', 'Waktu Pesanan Dibuat',
       'Waktu Pembayaran Dilakukan', 'SKU Induk', 'Nama Produk',
       'Nomor Referensi SKU', 'Nama Variasi', 'Harga Awal',
       'Harga Setelah Diskon', 'Jumlah', 'Total Harga Produk', 'Total Diskon',
       'Diskon Dari Penjual', 'Diskon Dari Shopee', 'Berat Produk',
       'Jumlah Produk di Pesan', 'Total Berat', 'Voucher Ditanggung Penjual',
       'Cashback Koin', 'Voucher Ditanggung Shopee', 'Paket Diskon',
       'Paket Diskon (Diskon dari Shopee)',
       'Paket Diskon (Diskon dari Penjual)', 'Potongan Koin Shopee',
       'Diskon Kartu Kredit', 'Ongkos Kirim Dibayar oleh Pembeli',
       'Total Pembayaran', 'Perkiraan Ongkos Kirim', 'Catatan dari Pembeli',
       'Catatan', 'Username (Pembeli)', 'Nama Penerima', 'No. Telepon',
       'Alamat Pengiriman', 'Kota/Kabupaten', 'Provinsi',
       'Waktu Pesanan Selesai'],
      dtype='object')

In [103]:
columns = ['Invoice',  
           'Product Name', 
           'Product Price (IDR)', 
           'Product Quantity', 
           'Shipping Fee (IDR)', 
           'Total Amount (IDR)',
           'Order Created Date', 
           'Courier Name', 
           'Order Status', 
           'Region/Province']

In [108]:
df.rename(columns = {'No. Pesanan':'Invoice',
                     'Status Pesanan':'Order Status', 
                     'Opsi Pengiriman':'Courier Name',
                     'Waktu Pembayaran Dilakukan':'Order Created Date',
                     'Nama Produk':'Product Name', 
                     'Harga Awal':'Product Price (IDR)',
                     'Jumlah':'Product Quantity', 
                     'Ongkos Kirim Dibayar oleh Pembeli':'Shipping Fee (IDR)',
                     'Total Pembayaran':'Total Amount (IDR)', 
                     'Provinsi':'Region/Province'}, 
                     inplace = True)

In [109]:
for i in df.columns:
    if i not in columns:
        df = df.drop([i], axis=1)

In [110]:
df = df[columns]

In [116]:
df

,Invoice,Product Name,Product Price (IDR),Product Quantity,Shipping Fee (IDR),Total Amount (IDR),Order Created Date,Courier Name,Order Status,Region/Province,Product Category
0,20010153Y8CW66,Tas Sekolah tahan air 15.6 inch,379000,45,2000,17057000,2020-01-01 05:19,JNE REG,Order Berhasil,Prop. Jawa Timur,Accessories
1,20010176X0XX76,Payung lipat 42 inch,42900,83,2000,3562700,2020-01-01 09:35,JNE REG,Order Berhasil,Prop. Kalimantan Barat,Accessories
2,20010176X0XX76,Baju Koko lengan pendek hitam,89900,8,2000,721200,2020-01-01 09:35,JNE REG,Order Berhasil,Prop. Kalimantan Barat,Pakaian
3,20010187I5JB87,Pashmina ceruty premium basic,34900,3,2000,106700,2020-01-01 12:28,JNE REG,Order Berhasil,Prop. Jawa Barat,Pakaian
4,20010190D4VD66,Baju Gamis bahan katun gold,79000,74,2000,5848000,2020-01-01 15:01,JNE Reguler (Cashless),Order Berhasil,Prop. Jawa Timur,Pakaian
...,...,...,...,...,...,...,...,...,...,...,...
11995,22123158L4VZ40,Seragam Sekolah SD paket lengkap,114900,7,2000,806300,2022-12-31 09:19,J&T Express,Order Berhasil,Prop. Bengkulu,Pakaian
11996,22123112G5AV78,Payung lipat 42 inch,42900,57,2000,2447300,2022-12-31 10:19,GoSend Same Day,Order Berhasil,Prop. Riau,Accessories
11997,22123115M1IN74,Tas Sekolah tahan air 15.6 inch,379000,8,2000,3034000,2022-12-31 16:44,J&T Express,Order Berhasil,Prop. Riau,Accessories
11998,22123139I3WU31,Sweater unisex kuning,99000,51,2000,5051000,2022-12-31 21:03,GrabExpress SameDay,Order Berhasil,Prop. Papua,Pakaian
11999,22123139I3WU31,Jas Hujan setelan bahan polymer,149000,37,2000,5515000,2022-12-31 21:03,GrabExpress SameDay,Order Berhasil,Prop. Papua,Pakaian

In [112]:
# Order Status
df['Order Status'] = df['Order Status'].apply(lambda x: 'Order Berhasil' if x=='Selesai' else 'Order Gagal')

In [114]:
def category(row):
   if 'Baju' in row['Product Name']:
      return 'Pakaian'
   if 'Pashmina' in row['Product Name']:
      return 'Pakaian'
   if 'Sweater' in row['Product Name']:
      return 'Pakaian'
   if 'Jas' in row['Product Name']:
      return 'Pakaian'
   if 'Seragam' in row['Product Name']:
      return 'Pakaian'
   if 'Batik' in row['Product Name']:
      return 'Pakaian'
   if 'Sepatu' in row['Product Name']:
      return 'Sepatu'
   return 'Accessories'

In [115]:
# Product Category
df['Product Category'] = df.apply(category, axis=1)

In [117]:
# Courier Service
df['Courier Service'] = df['Courier Name'].apply(lambda x: 'Same Day' if 'Same' in x else 'Regular')

In [127]:
# Courier Name

def courier_name(row):
   if 'Go' in row['Courier Name']:
      return 'GO-JEK'
   if 'JNE' in row['Courier Name']:
      return 'JNE'
   if 'SiCepat' in row['Courier Name']:
      return 'SiCepat'
   if 'Grab' in row['Courier Name']:
      return 'Grab'
   if 'J&T' in row['Courier Name']:
      return 'J&T'
   
df['Courier Name'] = df.apply(courier_name, axis=1)

In [118]:
# Ecommerce
df['ECommerce'] = 'Shopee'

In [124]:
# Extract Province
df['Region/Province'] = df['Region/Province'].str.extract(r"([^(Prop.\s)](\w+).+)")[0]
df['Region/Province'] = df['Region/Province'].apply(lambda x: 'Papua' if 'apua' in x else x)

In [119]:
# Date Format
df['Date']= df['Order Created Date']
df['Date'] = pd.to_datetime(df.Date, format='%Y-%m-%d %H:%M')
df['Date'] = df['Date'].dt.strftime('%d-%m-%Y')
df = df.drop(['Order Created Date'], axis=1)
df.rename(columns = {'Date':'Order Created Date'}, inplace =True)

In [121]:
new_cols_order = ['Invoice', 'Product Name', 'Product Category', 'Product Price (IDR)', 'Product Quantity',
       'Shipping Fee (IDR)', 'Total Amount (IDR)',  'Order Created Date', 'Courier Name', 'Courier Service',
       'Order Status', 'Region/Province', 'ECommerce']

In [122]:
df = df[new_cols_order]

In [128]:
df

,Invoice,Product Name,Product Category,Product Price (IDR),Product Quantity,Shipping Fee (IDR),Total Amount (IDR),Order Created Date,Courier Name,Courier Service,Order Status,Region/Province,ECommerce
0,20010153Y8CW66,Tas Sekolah tahan air 15.6 inch,Accessories,379000,45,2000,17057000,01-01-2020,JNE,Regular,Order Berhasil,Jawa Timur,Shopee
1,20010176X0XX76,Payung lipat 42 inch,Accessories,42900,83,2000,3562700,01-01-2020,JNE,Regular,Order Berhasil,Kalimantan Barat,Shopee
2,20010176X0XX76,Baju Koko lengan pendek hitam,Pakaian,89900,8,2000,721200,01-01-2020,JNE,Regular,Order Berhasil,Kalimantan Barat,Shopee
3,20010187I5JB87,Pashmina ceruty premium basic,Pakaian,34900,3,2000,106700,01-01-2020,JNE,Regular,Order Berhasil,Jawa Barat,Shopee
4,20010190D4VD66,Baju Gamis bahan katun gold,Pakaian,79000,74,2000,5848000,01-01-2020,JNE,Regular,Order Berhasil,Jawa Timur,Shopee
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,22123158L4VZ40,Seragam Sekolah SD paket lengkap,Pakaian,114900,7,2000,806300,31-12-2022,J&T,Regular,Order Berhasil,Bengkulu,Shopee
11996,22123112G5AV78,Payung lipat 42 inch,Accessories,42900,57,2000,2447300,31-12-2022,GO-JEK,Same Day,Order Berhasil,Riau,Shopee
11997,22123115M1IN74,Tas Sekolah tahan air 15.6 inch,Accessories,379000,8,2000,3034000,31-12-2022,J&T,Regular,Order Berhasil,Riau,Shopee
11998,22123139I3WU31,Sweater unisex kuning,Pakaian,99000,51,2000,5051000,31-12-2022,Grab,Same Day,Order Berhasil,Papua,Shopee
11999,22123139I3WU31,Jas Hujan setelan bahan polymer,Pakaian,149000,37,2000,5515000,31-12-2022,Grab,Same Day,Order Berhasil,Papua,Shopee

In [129]:
df.to_csv('Shopee.csv', index=False)